language: python

cache:
  pip: true
  apt: true

python:
  - "3.6"

addons:
  apt:
    sources:
    - travis-ci/sqlite3
    packages:
    - sqlite3

install:
  - pip install -r requirements.txt
  - pip install codecov

script:
  - coverage run tests.py

after_success:
  - codecov

notifications:
  webhooks: https://tny.site/travis/
  email: false
